site_name: camIO
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences